#!/bin/sh
#
# @name STARS PhoenixDrone
#
# @type VTOL Duo Tailsitter
#

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=stars_ts}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=phoenixdrone}

param set-default SIM_GZ_EN 1 # Gazebo bridge

param set-default MAV_TYPE 19

param set-default CA_AIRFRAME 4

param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0.195
param set-default CA_ROTOR0_KM -0.023
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -0.195
param set-default CA_ROTOR1_KM 0.023

param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_Y 0.5
param set-default CA_SV_CS1_TYPE 6
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_Y -0.5

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 0
param set-default SIM_GZ_EC_FUNC4 0
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 1000
param set-default SIM_GZ_EC_MIN4 1000

param set-default SIM_GZ_EC_MAX1 800
param set-default SIM_GZ_EC_MAX2 800
param set-default SIM_GZ_EC_MAX3 2000
param set-default SIM_GZ_EC_MAX4 2000

param set-default SIM_GZ_SV_MINA1 30
param set-default SIM_GZ_SV_MAXA1 -30
param set-default SIM_GZ_SV_MINA2 60
param set-default SIM_GZ_SV_MAXA2 -60

# Direct actuator offboard control is not visible to the multicopter land
# detector's thrust check, so it can auto-disarm while hovering.
param set-default COM_DISARM_LAND -1

param set-default FD_FAIL_R 70

param set-default FW_P_TC 0.6

param set-default FW_PR_I 0.3
param set-default FW_PR_P 0.5
param set-default FW_PSP_OFF 2
param set-default FW_RR_FF 0.1
param set-default FW_RR_I 0.1
param set-default FW_RR_P 0.2
param set-default FW_YR_FF 0 # make yaw rate controller very weak, only keep default P
param set-default FW_YR_I 0
param set-default FW_THR_TRIM 0.35
param set-default FW_THR_MAX 0.8
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 6
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 1.6
param set-default FW_AIRSPD_STALL 10
param set-default FW_AIRSPD_MIN 14
param set-default FW_AIRSPD_TRIM 18
param set-default FW_AIRSPD_MAX 22

param set-default MC_AIRMODE 2
param set-default MAN_ARM_GESTURE 0 # required for yaw airmode
param set-default MC_ROLL_P 6.0
param set-default MC_ROLLRATE_P 0.12
param set-default MC_ROLLRATE_I 0.002
param set-default MC_ROLLRATE_D 0.003
param set-default MC_PITCH_P 4.5
param set-default MC_PITCHRATE_P 0.3
param set-default MC_PITCHRATE_I 0.002
param set-default MC_PITCHRATE_D 0.003
param set-default MC_YAW_P 3.8
param set-default MC_YAWRATE_P 0.22
param set-default MC_YAWRATE_I 0.02
param set-default MC_YAWRATE_D 0.0

param set-default MPC_XY_P 0.2
param set-default MPC_TKO_SPEED 0.8
param set-default MPC_ACC_HOR_MAX 1
param set-default MPC_TILTMAX_AIR 30
param set-default MPC_THR_MAX 1

param set-default VT_ARSP_TRANS 15
param set-default VT_B_TRANS_DUR 5
param set-default VT_FW_DIFTHR_EN 7
param set-default VT_FW_DIFTHR_S_Y 1
param set-default VT_F_TRANS_DUR 1.5
param set-default VT_TYPE 0

param set-default WV_EN 0

param set-default EKF2_FUSE_BETA 0
